"""Create Zendesk tickets through its REST API when an anomaly is detected."""

import datetime
from typing import Optional, Tuple

import requests

from app.anomaly import Anomaly
from app.config import Client, Settings

# OAuth access token cache in process memory: {subdomain: (token, expires_at_utc)}.
_token_cache = {}


def _get_access_token(settings: Settings) -> str:
    """Obtain an OAuth access token through client_credentials and reuse it
    while it has not expired."""
    cached = _token_cache.get(settings.zendesk_subdomain)
    if cached and cached[1] > datetime.datetime.utcnow():
        return cached[0]

    url = f"https://{settings.zendesk_subdomain}.zendesk.com/oauth/tokens"
    payload = {
        "grant_type": "client_credentials",
        "client_id": settings.zendesk_client_id,
        "client_secret": settings.zendesk_client_secret,
        "scope": settings.zendesk_oauth_scope,
    }
    response = requests.post(url, json=payload, timeout=15)
    response.raise_for_status()
    data = response.json()

    token = data["access_token"]
    expires_in = data.get("expires_in", 3600)
    # Use a 60-second safety margin to avoid using a nearly expired token.
    expires_at = datetime.datetime.utcnow() + datetime.timedelta(seconds=max(expires_in - 60, 0))
    _token_cache[settings.zendesk_subdomain] = (token, expires_at)
    return token


def _build_description(client: Client, anomaly: Anomaly, account_balance: str) -> str:
    return (
        f"A growing error trend was detected in the client's Twilio account.\n\n"
        f"Client: {client.name} ({client.twilio_account_sid})\n"
        f"Twilio Account SID: {client.twilio_account_sid}\n"
        f"Error code: {anomaly.error_code}\n"
        f"Current count (latest run): {anomaly.current_count}\n"
        f"Historical average (baseline): {anomaly.baseline_avg:.1f}\n"
        f"Historical standard deviation: {anomaly.baseline_stddev:.1f}\n"
        f"Increase over baseline: {anomaly.pct_increase:.1f}%\n"
        f"Consecutive increasing runs: {anomaly.streak}\n"
        f"Account balance at detection time: {account_balance}\n"
        f"Detection time (UTC): {datetime.datetime.utcnow().isoformat()}\n\n"
        f"This ticket was automatically generated by the proactive-customer-care "
        f"anomaly monitoring system."
    )


def create_ticket(
    client: Client, anomaly: Anomaly, settings: Settings, account_balance: str
) -> Tuple[Optional[str], Optional[str]]:
    """Create a Zendesk ticket. Return (ticket_id, ticket_url), or (None, None) on failure."""
    if not settings.zendesk_subdomain:
        return None, None

    url = f"https://{settings.zendesk_subdomain}.zendesk.com/api/v2/tickets.json"
    headers = {"Authorization": f"Bearer {_get_access_token(settings)}"}

    payload = {
        "ticket": {
            "subject": (
                f"[Monitoring] Increase in errors ({anomaly.error_code}) "
                f"in {client.name}'s account"
            ),
            "comment": {"body": _build_description(client, anomaly, account_balance)},
            "priority": settings.zendesk_ticket_priority,
            "tags": ["anomaly-detection", "twilio", "auto-generated", client.twilio_account_sid],
        }
    }
    if client.zendesk_organization_id:
        payload["ticket"]["organization_id"] = client.zendesk_organization_id

    response = requests.post(url, headers=headers, json=payload, timeout=15)
    response.raise_for_status()

    data = response.json()
    ticket_id = str(data["ticket"]["id"])
    ticket_url = f"https://{settings.zendesk_subdomain}.zendesk.com/agent/tickets/{ticket_id}"
    return ticket_id, ticket_url
